### ISSUE TITLE
Random red lines on image when filling out of bounds

### ISSUE THREAD

**Issue by PragyaM** [PragyaM/FITS2D#2]
Anonymous created an issue 2015-06-18
If I attempt to use the Mask bucket tool and click outside the image bounds but within the drawing area (say to the right of the image), then I get a random red line on the image. It also causes and exception.
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException: -1, 646 at com.sun.prism.Image$BaseAccessor.getIndex(Image.java:933) at com.sun.prism.Image$BaseAccessor.getArgb(Image.java:973) at com.sun.prism.Image.getArgb(Image.java:642) at javafx.scene.image.Image$2.getArgb(Image.java:1161) at javafx.scene.image.Image$2.getColor(Image.java:1166) at services.FillRegion.doFill(FillRegion.java:49) at services.FillRegion.doFill(FillRegion.java:59) ... A billion more of the same

**Comment by PragyaM** [comment]
This also happens when user has zoomed over the image before using the bucket tool
986d1c2 issue 2: limit bounds of annotation canvas to the image bounds and respect zooming and panning transformations. User can no longer draw outside of image bounds.
